
-- FIKRLAR JADVALI
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- RLS Qoidalarini yoqish
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Reviews hamma ko'ra oladi" ON public.reviews 
FOR SELECT USING (true);

CREATE POLICY "User o'z fikrini qoldira oladi" ON public.reviews 
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- INDEXLAR (Tezlik uchun)
CREATE INDEX IF NOT EXISTS idx_reviews_product ON public.reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
