
-- 1. Kuryer tasdiqlashini avtomatlashtirish funksiyasi
CREATE OR REPLACE FUNCTION handle_courier_role_change()
RETURNS TRIGGER AS $$
BEGIN
  -- Agar role 'courier'ga o'zgarsa, avtomatik tasdiqlash
  IF (NEW.role = 'courier' AND (OLD.role IS DISTINCT FROM NEW.role)) THEN
    NEW.is_approved := true;
  END IF;

  -- Agar role 'courier'dan boshqa narsaga o'zgarsa, tasdiqni bekor qilish
  IF (OLD.role = 'courier' AND NEW.role != 'courier') THEN
    NEW.is_approved := false;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. Triggerni bog'lash
DROP TRIGGER IF EXISTS tr_courier_approval ON public.profiles;
CREATE TRIGGER tr_courier_approval
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION handle_courier_role_change();

-- 3. Kuryer loglari uchun jadval (agar yo'q bo'lsa)
CREATE TABLE IF NOT EXISTS public.courier_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    courier_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    action_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
